# List all recipies
default:
    just --list --unsorted

# Run Bison
bison:
    bison --defines=token.h --output=parser.c parser.bison

# flex
flex:
    flex -o scanner.c scanner.flex

# flex based binary. To debug tokens.
main-flex: flex
    gcc scan_main.c scanner.c -o scanner


# Produce executable
main: flex bison
    gcc main.c scanner.c parser.c -o a.out
